# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wish_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_hired',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
